SOC-5523 : Social RDBMS migration logs are too verbose when no data
exoplatform/social pull request #430
Opened 2016-12-13 16:34 UTC by aboughzela

2016-12-13 22:39 UTC, thomasdelhomenie commented
When I try to build the PR (only the module component/core-jpa), the build is stuck after 

[SOC-MIGRATION-RDBMS] INFO org.exoplatform.social.core.jpa.updater.RDBMSMigrationManager - No Social data to migrate from JCR to RDBMS

The thread is stuck :

"main" #1 prio=5 os_prio=0 tid=0x00007f0c50007800 nid=0x5ea2 waiting on condition [0x00007f0c59334000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000f469c350> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.exoplatform.social.core.jpa.concurrency.AsynMigrateEmptyDataTest.testMigrationEmptyData(AsynMigrateEmptyDataTest.java:34)

2016-12-13 22:40 UTC, thomasdelhomenie requested changes
When I try to build the PR (only the module component/core-jpa), the build is stuck after

[SOC-MIGRATION-RDBMS] INFO org.exoplatform.social.core.jpa.updater.RDBMSMigrationManager - No Social data to migrate from JCR to RDBMS

The thread is stuck :

"main" #1 prio=5 os_prio=0 tid=0x00007f0c50007800 nid=0x5ea2 waiting on condition [0x00007f0c59334000]
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00000000f469c350> (a java.util.concurrent.CountDownLatch$Sync)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
at org.exoplatform.social.core.jpa.concurrency.AsynMigrateEmptyDataTest.testMigrationEmptyData(AsynMigrateEmptyDataTest.java:34)

2016-12-14 10:04 UTC, aboughzela commented
PR update : Decrements the count of the latch

2016-12-14 12:40 UTC, thomasdelhomenie approved these changes

2016-12-14 13:11 UTC, closed without merging